### ISSUE TITLE
Switching directories in multiple buffers do not work anymore

### ISSUE THREAD

**Issue by fab6** [Shougo/defx.nvim#114] opened 2019-04-01 10:48 UTC
# Problems summary
After window split the directories get mixed up.

## Expected
Consistent directory handling (or wrong command by myself!?). See description below.

## Environment Information

 * defx version(SHA1):
just updated
 * OS:
linux opensuse
 * neovim/Vim version:
NVIM v0.4.0-148-g95fa71c6d

## The reproduce ways from neovim/Vim starting (Required!)
1) Open defx
2) split vertical with
```
:Defx -sort="Time" -split="vertical" -new -auto-cd `expand('%:p:h')` -search=`expand('%:p')` 
```
3) go to left window and change directory
4) go back to righ window and create a another new Defx e.g. in a new tab with:
```
:Defx -sort="Time" -split="tab" -new -auto-cd `expand('%:p:h')` -search=`expand('%:p')` <CR>
```

The new tab should have the same directory as the right window, but it has now for some weeks the same directory as the left window.
New tab has the same directory as the right window.

**Comment by Shougo** [comment] 2019-04-01 13:05
`go to left window and change directory`

It must be `lcd` instead of `cd`.

```
The new tab should have the same directory as the right window, but it has now for some weeks the same directory as the left window.
New tab has the same directory as the right window.
```

It is the feature.  Why?  `cd` changes the right window's cwd.
`expand('%:p:h')` use window's current directory to get full path.

Closing.

**Comment by fab6** [comment] 2019-04-01 13:25
thank you for the quick response!

Sorry for the confusion, in my last sentence I mixed up left and right.

I wrote:  "New tab has the same directory as the right window."
but I wanted to write: "New tab has the same directory as the left window."

I am not sure if I understand your response. 

In step 4 I am back in the right window from which I want to open up e.g. a new tab with a new Defx. This new Defx should have the same directory as the one from which I started the command, which is for this case the directory of the right window. And as I am starting from the right window "expand('%:p:h')" should exactly do this!?

I am not sure, where lcd and cd get involved, I am only using the above commands.

Thanks!

**Comment by fab6** [comment] 2019-04-01 14:56
one additional comment:
In step 3 I change the directory with defx's command "defx#do_action('open')" and not with "cd"

Thanks!

**Comment by Shougo** [comment] 2019-04-02 00:07
> And as I am starting from the right window "expand('%:p:h')" should exactly do this!?

Yes.  You should check the current directory in the right window.

**Comment by fab6** [comment] 2019-04-02 07:55
I think there is a misunderstanding...I attached a more visual example, which might make it a bit more clear.
[defx.pptx](https://github.com/Shougo/defx.nvim/files/3032851/defx.pptx)

**Comment by Shougo** [comment] 2019-04-02 12:55
OK.  If so, please create the reproduce-able minimal vimrc and reproduce ways again.

If not, I will ignore it.

For example:

https://github.com/Shougo/defx.nvim/issues/111

Your initial report is wrong and you have not upload the reproduce-able vimrc.
So I cannot reproduce your problem and misunderstanding. 

> Warning: I will close the issue without the minimal init.vim and the reproduction instructions.

Have you read the warning?

**Comment by fab6** [comment] 2019-04-02 14:34
Ok.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
my init.vim:
:set guioptions=M
"==================================================================================================
set runtimepath+=/home/fbraenns/.nvim_min/
"--------------------------------------------------------------------------------------------------
call plug#begin('/home/fbraenns/.nvim_min/vimplug')
Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

my ftplugin defx_mappings.vim for easier reproduction:
nnoremap <silent><buffer><expr> l defx#do_action('open')
map <silent><buffer>X :Defx -sort="Time" -split="tab" -new -auto-cd `expand('%:p:h')` -search=`expand('%:p')` <CR>
map <silent><buffer>gx :Defx -sort="Time" -split="vertical" -new -auto-cd `expand('%:p:h')` -search=`expand('%:p')` <CR>

## The reproduce ways from neovim/Vim starting (Required!)
1) start neovim and open :Defx
2) split Defx with keybing "gx"
3) go into any directory with keybinding "l" in left window
4) Switch to right window with keybding "<C-w>l"
5) Press keybding "X" in right window to open a new Defx in a new tab

**Comment by fab6** [comment] 2019-04-02 14:46
Step 4 is wrong as the change window keybinding is partly removed, I try it again <<C-w>-l>

**Comment by fab6** [comment] 2019-04-02 14:48
<sldfkj>

**Comment by fab6** [comment] 2019-04-02 14:49
For step 4 I use the standard keybinding to change to the right window. In my post above the keybinding part with C-w was removed.

**Comment by Shougo** [comment] 2019-04-02 14:52
OH, it is not minimal and reproduce-able.

Please read this again and compare with yours.
https://github.com/Shougo/defx.nvim/issues/111

**Comment by Shougo** [comment] 2019-04-02 14:55
This is the read minimal vimrc

```vim
set runtimepath+=~/work/defx.nvim/

filetype plugin indent on
syntax enable

colorscheme desert

autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  nnoremap <silent><buffer><expr> l defx#do_action('open')
  map <silent><buffer>X :Defx -sort="Time" -split="tab" -new -auto-cd `expand('%:p:h')` -search=`expand('%:p')`<CR>
  map <silent><buffer>gx :Defx -sort="Time" -split="vertical" -new -auto-cd `expand('%:p:h')` -search=`expand('%:p')`<CR>
endfunction
```

**Comment by fab6** [comment] 2019-04-02 15:06
Ok, I got it now. Thank you.

**Comment by Shougo** [comment] 2019-04-03 12:38
Fixed.

**Closed** 2019-04-03 12:38 UTC

**Comment by fab6** [comment] 2019-04-05 10:51
thanks
