### ISSUE TITLE
Doesn't open new directory after defx buffer closed

### ISSUE THREAD

**Issue by thecontinium** [Shougo/defx.nvim#227] opened 2020-07-04 14:21 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
```
$ nvim
:Defx /tmp
:q
:Defx ~/

```
opens `/tmp`

## Expected

open `~`

## Environment Information

 * defx version(SHA1): latest

 * OS: macos

 * neovim/Vim version: HEAD

 * `:checkhealth` or `:CheckHealth` result(neovim only): ok

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

all

**Comment by Shougo** [comment] 2020-07-05 01:57
Please upload the minimal vimrc!

**Comment by Shougo** [comment] 2020-07-05 01:59
The minimal vimrc

```vim
set runtimepath+=~/work/defx.nvim
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/
```

`:Defx /tmp`
`:bd`
`:Defx /`

I don't reproduce the problem.

**Comment by Shougo** [comment] 2020-07-05 02:00
> Warning: I will close the issue without the minimal init.vim and the reproduction instructions.

Have you read it?  Really?

> Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
> all

It means I can close the issue if I cannot repduce the problem with any of vimrc.

**Comment by mn-dimension** [comment] 2020-07-05 07:11
With:

```
if &compatible | set nocompatible | endif

" Set configuration paths
let $VIMRC_DIR = fnamemodify(expand($MYVIMRC), ':h')
let $BUNDLE_DIR = $VIMRC_DIR . '/bundle'
let $DEIN_DIR = $BUNDLE_DIR . '/repos/github.com/Shougo/dein.vim'
let g:python3_host_prog = $PYENV_ROOT . '/versions/neovim/bin/python'

" Install dein.vim
if ! isdirectory($DEIN_DIR)
        execute '!git clone https://github.com/Shougo/dein.vim' expand($DEIN_DIR)
endif
execute 'set runtimepath+='.substitute(
        \ fnamemodify($DEIN_DIR, ':p') , '/$', '', '')

" Add plugins to bundle
call dein#begin($BUNDLE_DIR, [ expand('<sfile>') ])
call dein#add('Shougo/Defx.nvim')
call dein#end()

if dein#check_install()
        call dein#install()
endif

filetype plugin indent on
syntax enable
call defx#custom#option('_', {
        \ 'resume': 1,
        \ 'winwidth': 25,
        \ 'split': 'vertical',
        \ 'direction': 'topleft',
        \ 'show_ignored_files': 0,
        \ 'columns': 'indent:git:icons:filename',
        \ 'root_marker': ' ',
        \ 'ignored_files':
        \     '.mypy_cache,.pytest_cache,.git,.hg,.svn,.stversions'
        \   . ',__pycache__,.sass-cache,*.egg-info,.DS_Store,*.pyc'
        \ })

```

```
$ nvim
:Defx /tmp
:q
:Defx /
```

/tmp shown as root

**Comment by mn-dimension** [comment] 2020-07-05 11:41
I get the fictionality I need removing the resume set to 1 so if this is the behaviour you expect with it set keep this closed.

Cheers

**Comment by Shougo** [comment] 2020-07-05 13:30
@mn-dimension You must upload the vimrc with initial report.
I cannot reproduce it without your information.  Please don't ignore it.

**Closed** 2020-07-05 13:44 UTC
Labels: cannot reproduce

**Comment by Shougo** [comment] 2020-07-05 13:47
Fixed.

**Comment by mn-dimension** [comment] 2020-07-05 16:27
fixed - thanks
