### ISSUE TITLE
some features

### ISSUE THREAD

**Issue by fab6** [Shougo/defx.nvim#4] opened 2018-01-23 19:55 UTC
Hi,
I am not in the position to ask for much, but I thought, I could add some wishes for the features based on my dired experience:
- Live-narrowing of search results (https://github.com/Fuco1/dired-hacks/blob/master/dired-narrow.el)
- Extension based highlight (https://github.com/Fuco1/dired-hacks#dired-rainbow)
- option to toggle the permissions/owner/groups
- option to have several independent buffers with the file manager in different directories open; similar like a dual pane file manager (I am not sure, if this was meant by double filer feature)
- speed; at the moment it seems, that vimfiler is compared to ranger, vifm, dired much slower to load a new directory when the directory has a lot (just checked for a cases with around 1000 files) of files
Thank you!

**Comment by kutsan** [comment] 2018-01-23 20:00
+1 for speed. It would be awesome if we get the fastest one out of this project.

**Comment by Shougo** [comment] 2018-01-24 03:18
> option to toggle the permissions/owner/groups

It can be implemented by columns feature.

**Comment by Shougo** [comment] 2018-01-24 03:19
> option to have several independent buffers with the file manager in different directories open; similar like a dual pane file manager (I am not sure, if this was meant by double filer feature)

The double(dual) pane file manager feature won't be supported.
But I am also double(dual) manager fun.
The alternative feature will be supported.

**Comment by Shougo** [comment] 2018-01-24 03:20
> speed; at the moment it seems, that vimfiler is compared to ranger, vifm, dired much slower to load a new directory when the directory has a lot (just checked for a cases with around 1000 files) of files
Thank you!

Of course, it is important.
I think defx.nvim will be faster than vimfiler.
Why?  You can compare the performance between denite.nvim and unite.vim.

**Comment by Shougo** [comment] 2018-01-24 03:22
> Extension based highlight (https://github.com/Fuco1/dired-hacks#dired-rainbow)

The highlight is the feature of column.
It may be customized by `defx#custom#column()`.

**Comment by Shougo** [comment] 2018-01-24 03:23
> Live-narrowing of search results (https://github.com/Fuco1/dired-hacks/blob/master/dired-narrow.el)

I will look the feature.

**Comment by Shougo** [comment] 2018-01-24 03:39
The extension based highlight should be dictionary.

The key is extension regex and the value is highlight.

**Comment by fab6** [comment] 2018-01-24 20:34
Great, thanks!

**Comment by kristijanhusak** [comment] 2018-08-01 12:02
Here's my list of some features that i'm missing:
* action to delete file/directory
* syntax highlighting
* Some configuration for the layout (for example, change + to some arrows, remove the root `-`, etc.)

**Comment by Shougo** [comment] 2018-08-01 14:12
> action to delete file/directory

> syntax highlighting

It will be implemented soon.

> Some configuration for the layout (for example, change + to some arrows, remove the root -, etc.)

It takes time.  Because, it is user customization.

**Comment by kristijanhusak** [comment] 2018-08-01 16:25
Also, i would like to have simple git integration at one moment, something like  https://github.com/Xuyuanp/nerdtree-git-plugin. I made similar thing for vim-dirvish https://github.com/kristijanhusak/vim-dirvish-git.
I don't know if you are interested in adding that to the plugin itself, if not, i'll probably work on the separate plugin to support this. Let me know your thoughts.

**Comment by Shougo** [comment] 2018-08-01 21:41
It should be implemented by column feature.
I don't add git column, but you can add it.

**Comment by Shougo** [comment] 2018-08-13 23:41
> speed; at the moment it seems, that vimfiler is compared to ranger, vifm, dired much slower to load a new directory when the directory has a lot (just checked for a cases with around 1000 files) of files

I have tested defx.nvim performance.
It is very fast.

I see no lag on 1000, 5000, 10000 files with defx.nvim.

Note: vimfiler is very slow....

**Comment by fab6** [comment] 2018-08-14 16:37
indeed, very fast, thanks

**Comment by Shougo** [comment] 2018-08-18 09:35
> History for directories

It is todo listed.

> Parent directory - cursor position

I have implemented the feature.  Please update.

> Independent defx buffer

It is todo listed.

> Change of working directory while navigating with defx

It is `-auto-cd` option in vimfiler?

**Comment by Shougo** [comment] 2018-08-18 09:54
I have implemented `-auto-cd` option.

> which could have the same directory-history...

It is impossible.

**Comment by petobens** [comment] 2018-08-18 13:29
> The double(dual) pane file manager feature won't be supported.
But I am also double(dual) manager fun.
The alternative feature will be supported.

@Shougo  so there will be a double filer feature? I think this is killer feature of vimfiler (especially to copy/paste/move files around).

**Comment by Shougo** [comment] 2018-08-18 15:04
It is not native feature, but you can emulate it.

**Comment by fab6** [comment] 2018-08-18 15:50
I am not sure, if the same is meant for defx emulation, but for vimfiler I used these mappings for double filer feature emulation:
1) To create an indepent vimfiler:
nmap <silent><buffer>gx :vs<CR> :VimFilerCreate -status -sort-type=Time<CR>
2) To copy from one to another vimfiler:
nmap <silent><buffer>C <Plug>(vimfiler_mark_current_line)<Plug>(vimfiler_clipboard_copy_file)<C-w>w<Plug>(vimfiler_clipboard_paste)
This works only for two vimfiler windows open at the same time.

And often I have multiple independent vimfiler windows/directories open while editing. 
I understand that something similar might be possible with defx. 
In addition, for quick copying the history option should help with defx a lot.

**Comment by fab6** [comment] 2018-08-18 15:55
I just updated, now I get:

error caught in async handler '/home/fbraenns/.nvim/vimplug/defx.nvim/rplugin/python3/defx:function:_defx_start [[['/home/fbraenns/'], {'auto_cd': False, 'cursor': 1}]]'                     
Traceback (most recent call last):                                                                                                                                                            
  File "/home/fbraenns/.nvim/vimplug/defx.nvim/rplugin/python3/defx/__init__.py", line 35, in start                                                                                           
    self._view = View(self._vim, args[0], args[1])                                                                                                                                            
  File "/home/fbraenns/.nvim/vimplug/defx.nvim/rplugin/python3/defx/view.py", line 25, in __init__                                                                                            
    self._context = Context(**context)                                                                                                                                                        
TypeError: __new__() missing 2 required positional arguments: 'targets' and 'args' 

Not sure, if it is my problem, but 'auto_cd' is involved...
I did not use auto-cd with vimfiler... oh, no,  yes, I set in my config: let g:vimfiler_enable_auto_cd = 1  
Thanks!

**Comment by Shougo** [comment] 2018-08-18 16:01
> TypeError: new() missing 2 required positional arguments: 'targets' and 'args'

Hm.  I think your context.py is old.
I cannot reproduce the error.

**Comment by Shougo** [comment] 2018-08-18 17:04
Or you python version is old.  Python 3.6.1+ is required.

**Comment by Shougo** [comment] 2018-08-18 17:10
> I understand that something similar might be possible with defx.

Yes.

**Comment by fab6** [comment] 2018-08-18 17:11
ok, yes, 3.6.1 is the issue, thanks

**Comment by fab6** [comment] 2018-08-18 17:11
ok, great

**Comment by Shougo** [comment] 2018-08-19 04:45
> syntax highlighting

I have added syntax highlight feature.

**Comment by Shougo** [comment] 2018-09-02 09:38
> Extension based highlight (https://github.com/Fuco1/dired-hacks#dired-rainbow)

It can be implemented type column.
Please read the implementation.

Note: column customization feature is needed though.

**Comment by zgpio** [comment] 2018-09-23 08:10
Is it possible to add a custom ignore file rule?
Is such a feature necessary?
I think it can work with `defx-action-toggle_ignored_files`.

**Comment by Shougo** [comment] 2018-09-23 09:01
> Is it possible to add a custom ignore file rule?

It is not implemented yet.
Because, it needs `defx#custom#option()` feature.

**Comment by Shougo** [comment] 2018-09-23 10:17
> option to have several independent buffers with the file manager in different directories open; similar like a dual pane file manager (I am not sure, if this was meant by double filer feature)

I will implement the feature later.

**Comment by Shougo** [comment] 2018-09-23 10:51
I have implemented the feature

**Comment by Shougo** [comment] 2018-09-23 11:28
> I saw the split option. I am not sure, but if it should result in two independent defx windows, this does not work yet for me.

If you want to do, you need to use `-new` option.
`-split` option means split defx buffer.

**Comment by fab6** [comment] 2018-09-23 11:36
Great, did not see it. Thanks!

**Comment by Shougo** [comment] 2018-09-24 09:03
> History for directories

>  similar like denite's file_mru, it would be great to have a quick option to go back to recent directories (listing only defx directories within the history)

I have implemented it.

Note: Denite.nvim is needed to jump history.

**Comment by zgpio** [comment] 2018-09-24 09:07
I read the source code, `Columns` should be customized order?

**Comment by Shougo** [comment] 2018-09-24 09:11
> I read the source code, Columns should be customized order?

You can customize the order.
Please use `-columns` option.

Note: The feature is same with vimfiler.

**Comment by Shougo** [comment] 2018-09-24 11:14
`Denite defx/history` on defx buffer.

**Comment by fab6** [comment] 2018-09-24 12:00
ok, got it... great!

**Comment by zgpio** [comment] 2018-09-24 12:33
Sorry, but I can't reorder columns, `:Defx -columns=type:mark:filename`

**Comment by Shougo** [comment] 2018-09-24 15:55
> Sorry, but I can't reorder columns, `:Defx -columns=type:mark:filename`

Reproduced.  I have fixed the problem.

**Comment by fab6** [comment] 2018-09-24 16:52
The history works great. Are there thoughts to extend it to a "local" and a kind of "global" history. I.e. at the moment the history gets 'lost' with the -new option and it would be great to still keep the "global" history.

**Comment by Shougo** [comment] 2018-09-24 21:41
>  Are there thoughts to extend it to a "local" and a kind of "global" history. I.e. at the moment the history gets 'lost' with the -new option and it would be great to still keep the "global" history.

I have fixed the problem.

**Comment by fab6** [comment] 2018-09-25 04:33
thanks

**Comment by petobens** [comment] 2019-01-02 05:20
> If you want to do, you need to use -new option.
-split option means split defx buffer.

@Shougo  I use `:Defx -split=vertical -winwidth=40` options in order to have vertical split buffer of 40 characters. I want to have two defx buffers one on top of the other respecting the 40 character limit. How can I achieve this with defx?. In vimfiler the `-double` option gives me exactly this:
![image](https://user-images.githubusercontent.com/2583971/50581085-ea176200-0e34-11e9-83b1-cc3d8af62b4f.png)

**Comment by petobens** [comment] 2019-01-02 14:56
Ok. I now can you use something like this to emulate double filer feature:
```viml
nnoremap <silent> <Leader>xdf :Defx -split=vertical -winwidth=40
            \ -columns=git:icons:filename:type:size -show-ignored-files
            \ -direction=topleft `expand('%:p:h')` -search=`expand('%:p')`<CR>
            \ :Defx -new -split=horizontal
            \ -columns=git:icons:filename:type:size -show-ignored-files<CR>
            \ :wincmd p<CR>
```
However when I make a change in one of the buffers (such a creating a directory as in the GIF) this change is not reflected on the other buffer:
![double](https://user-images.githubusercontent.com/2583971/50597209-58841080-0e85-11e9-9e7a-2aafa596e5fe.gif)

Is there a way to have both buffers updated?

**Comment by Shougo** [comment] 2019-01-02 15:13
I have added WinEnter redraw.  Please update defx.

**Comment by Shougo** [comment] 2019-01-03 11:50
Almost requested features are already implemented.  Closing.

**Closed by Shougo** 2019-01-03 11:50 UTC
Labels: enhancement

**Comment by Shougo** [comment] 2019-01-05 11:15
> Instead of redrawing upon entering a window, is it possible to redraw all other defx buffers whenever the current defx buffer is modified with a create/delete/rename operation?

Sorry.  I don't want to implement it.

**Comment by Shougo** [comment] 2019-01-05 11:16
> Do you plan to implement the tree feature? Should we open another issues for that?

Tree feature is already requested in it.

https://github.com/Shougo/defx.nvim/issues/13

**Comment by petobens** [comment] 2019-01-05 15:07
Ok. Thanks!

**Comment by zgpio** [comment] 2019-04-04 07:22
> Ok. I now can you use something like this to emulate double filer feature: 
> ...

@petobens @Shougo 
I found that the double file browser can be implemented with this command `:Defx ~ ~/.vim`. Is my understanding of the two file browser correct?
![image](https://user-images.githubusercontent.com/19503791/55536759-26d14e80-56ed-11e9-938a-d9c2a2efd627.png)

**Comment by Shougo** [comment] 2019-04-04 12:31
> I found that the double file browser can be implemented with this command `:Defx ~ ~/.vim`.

It works.  But another solution is here.

```vim
nnoremap <silent><buffer><expr> <Tab> winnr('$') != 1 ?
\ ':<C-u>wincmd w<CR>' :
\ ':<C-u>Defx -buffer-name=temp -split=vertical<CR>'
```
