### ISSUE TITLE
Cannot map keys in neovim

### ISSUE THREAD

**Issue by hypghzy** [Shougo/defx.nvim#245] opened 2020-09-03 10:30 UTC
could not map the keys. other normal configs could work.

## Environment Information

 * plugin version(SHA1): 1.0

 * OS:deepin

 * neovim/Vim version: NVIM v0.3.4

 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#defx#check
===============================
## defx.nvim
    - OK: has("python3") was successful
    - OK: Python 3.6.1+ was successful

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

init.vim
```
  0 call plug#begin('~/.vim/plugged')
  1         if has('nvim')
  2           Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins' }
  3         else
  4           Plug 'Shougo/defx.nvim'
  5           Plug 'roxma/nvim-yarp'
  6           Plug 'roxma/vim-hug-neovim-rpc'
  7         endif
  8 call plug#end()
  9 
 10 autocmd FileType defx call s:defx_my_settings()
 11 function! s:defx_my_settings() abort
 12   " Define mappings
 13   nnoremap <silent><buffer><expr> <CR>
 14   \ defx#do_action('open')
 15   nnoremap <silent><buffer><expr> l
 16   \ defx#do_action('open')
 17 endfunction
```

Sorry, I do not know how to implement the following requirements.

## The reproduce ways from neovim/Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment] 2020-09-03 10:45
> could not map the keys. other normal configs could work.

What are `the keys`?
Please explain it more clearly.

We have not ESP skills.

**Comment by Shougo** [comment] 2020-09-03 10:47
I have tested it and works.

```vim
set runtimepath+=~/work/defx.nvim
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/

augroup user_plugin_defx
  autocmd!
  " Define defx window mappings
  autocmd FileType defx call <SID>defx_mappings()
augroup END

function! s:defx_mappings() abort
  " Define mappings
  nnoremap <silent><buffer><expr> <CR>
        \ defx#do_action('open')
  nnoremap <silent><buffer><expr> l
        \ defx#do_action('open')
endfunction
```

You need to upload reproduce instructions.  Please read other issues.

**Comment by Shougo** [comment] 2020-09-03 10:47
I have closed it.  Because it works for me with minimal vimrc.

**Closed by Shougo** 2020-09-03 10:47 UTC

**Comment by hypghzy** [comment] 2020-09-06 02:23
Sorry, I was traped by other issues, that I could not reply on time. Thank you so much for your answer. I was not able to understand what 'reproduce' mean, which caused that I did not upload it. 
I did not do anything that except implemented the very basic configureation that I put on.  I tried to clear all distractions, so I cleared my init.vim, only left the vim-plugin bundle and the defx configuration, and I olny mapped 'L' to 'open' for testing. I open the vim, us :Defx to turn on the filetree, but it only move the cursor to the right while I pressed 'L' key, it did not open the sub-folder as expected.

After read the script you have commented to this issue, I noticed that mu vim-plugin did not install nvim-yarp and vim-hug-neovim-rpc due to the if statement, but the mapping still not work after I have installed thses boundles manuly and added the set runtimepath into my init.vim. 

It will be very much appreciated if you could tell me is there anything that I did wrong or I can do to fix this issue.

Sorry again for the dely.
regards.

**Comment by Shougo** [comment] 2020-09-06 06:14
nvim-yarp and vim-hug-neovim-rpc is not needed in neovim.

> I did not do anything that except implemented the very basic configureation that I put on. I tried to clear all distractions, so I cleared my init.vim, only left the vim-plugin bundle and the defx configuration, and I olny mapped 'L' to 'open' for testing. I open the vim, us :Defx to turn on the filetree, but it only move the cursor to the right while I pressed 'L' key, it did not open the sub-folder as expected.

I think `L` key is not mapped.
`:verbose nmap l`

Please check your callback function `s:defx_mappings()` is really called.

**Comment by Shougo** [comment] 2020-09-06 06:15
I think you don't test the minimal vimrc.
Please test the minimal vimrc!

**Comment by hypghzy** [comment] 2020-09-06 23:41
> nvim-yarp and vim-hug-neovim-rpc is not needed in neovim.
> 
> > I did not do anything that except implemented the very basic configureation that I put on. I tried to clear all distractions, so I cleared my init.vim, only left the vim-plugin bundle and the defx configuration, and I olny mapped 'L' to 'open' for testing. I open the vim, us :Defx to turn on the filetree, but it only move the cursor to the right while I pressed 'L' key, it did not open the sub-folder as expected.
> 
> I think `L` key is not mapped.
> `:verbose nmap l`
> 
> Please check your callback function `s:defx_mappings()` is really called.

I tried this commend, it returned no mapping found.



> > It will be very much appreciated if you could tell me is there anything that I did wrong or I can do to fix this issue.
> 
> I think you don't test the minimal vimrc.
> Please test the minimal vimrc!
> 
> > I was not able to understand what 'reproduce' mean, which caused that I did not upload it.
> 
> I have said `Please read other issues`. Have you read other issues in defx.nvim??
> Please compare `The reproduce ways from neovim/Vim starting (Required!)` section.

I'm not quite sure what "minimal vimrc" means, but I did not creat a vimrc file, and the script I copied into this issue is basically every single line in my init.vim.

I can format the reproduce now
1. vim .config/nvim/init.vim
2. vim command: :Defx
3. l

![图片](https://user-images.githubusercontent.com/62455743/92337609-f237a280-f0e9-11ea-9093-e28c22d3ad1c.png)

**Comment by hypghzy** [comment] 2020-09-06 23:58
I just tried to generate a logfile

1.    export NVIM_PYTHON_LOG_FILE=/tmp/log
2.    export NVIM_PYTHON_LOG_LEVEL=DEBUG
3.    nvim -u ~/.config/nvim/init.vim test.m
4.    i
5.    typ in some words
6.    :Defx
7.    lllllll
8.    :q 
9.    :q 
10.    cat /tmp/log_py3_rplugin
11.    got nothing
I'm not sure where I did it wrong

**Comment by Shougo** [comment] 2020-09-07 00:06
OK.  I get the reason.
Please look your screenshot carefully.

```vim
augroup user_plugin_defx
  autocmd!
  " Define defx window mappings
  autocmd FileType defx call <SID>defx_settings()
augroup END
```

You call `s:defx_settings()` but your mappings are defined in `s:defx_mappings()` !!

**Comment by hypghzy** [comment] 2020-09-07 00:40
sorry I copied the missing part of my config from your script, fogrot to check other parts.

> I have tested it and works.
> 
> ```viml
> set runtimepath+=~/work/defx.nvim
> set runtimepath+=~/work/nvim-yarp/
> set runtimepath+=~/work/vim-hug-neovim-rpc/
> 
> augroup user_plugin_defx
>   autocmd!
>   " Define defx window mappings
>   autocmd FileType defx call <SID>defx_mappings()
> augroup END
> 
> function! s:defx_mappings() abort
>   " Define mappings
>   nnoremap <silent><buffer><expr> <CR>
>         \ defx#do_action('open')
>   nnoremap <silent><buffer><expr> l
>         \ defx#do_action('open')
> endfunction
> ```
> 
> You need to upload reproduce instructions. Please read other issues.

I have tried both two configs, one is from the config you posted here, one is from the defx-examples, they all got the same old result.
![图片](https://user-images.githubusercontent.com/62455743/92338826-05e70700-f0f2-11ea-80db-d9be943d63c6.png)

**Comment by Shougo** [comment] 2020-09-07 00:42
The config should work.  It is really does not work??
Please test other people.

**Comment by Shougo** [comment] 2020-09-07 00:44
And please upload the result by asciinema.org.

**Comment by hypghzy** [comment] 2020-09-07 00:49
> And please upload the result by asciinema.org.
> 
> Ah, please use the latest version of neovim. Your neovim version is too old.

I install it from the apt-repository i'm using, I will try to install it again via offical git, thank you for your help.

**Comment by hypghzy** [comment] 2020-09-07 02:09
I managed to change my neovim into 0.4.4, the mapping could work now, thank you for the help.
I suggest maybe you could change the the required neovim version in Installation requirement into a higher verion.

**Comment by Shougo** [comment] 2020-09-07 03:15
Oh, OK.
