### ISSUE TITLE
Defx open file the buffer nothing to show

### ISSUE THREAD

**Issue by glepnir** [Shougo/defx.nvim#212] opened 2020-05-29 14:55 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Open the defx then open a file,the buffer will show nothing

## Expected
works fine

## Environment Information

 * defx version(SHA1): the latest

 * OS: macos 10.15.5

 * neovim/Vim version: NVIM v0.5.0-nightly

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript entry lib/attach.js found
  - OK: Service started

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript entry lib/attach.js found
  - OK: Service started

health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 1ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: macOS-clipboard

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.7.7
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.3.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - WARNING: `perl` and `cpanm` must be in $PATH.
    - ADVICE:
      - Install Perl and cpanminus and verify that `perl` and `cpanm` commands work.


```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
call plug#begin('~/.vim/plugged')
Plug 'Shougo/defx.nvim'
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
call plug#end()

let g:mapleader="\<Space>"

call defx#custom#option('_', {
	\ 'resume': 1,
	\ 'winwidth': 30,
	\ 'split': 'vertical',
	\ 'direction': 'topleft',
	\ 'show_ignored_files': 0,
	\ 'columns': 'indent:git:icons:filename',
	\ 'root_marker': ' ',
	\ 'profile': 1,
	\ })

call defx#custom#column('git', {
	\   'indicators': {
	\     'Modified'  : '•',
	\     'Staged'    : '✚',
	\     'Untracked' : 'ᵁ',
	\     'Renamed'   : '≫',
	\     'Unmerged'  : '≠',
	\     'Ignored'   : 'ⁱ',
	\     'Deleted'   : '✖',
	\     'Unknown'   : '⁇'
	\   }
	\ })

call defx#custom#column('mark', { 'readonly_icon': '', 'selected_icon': '' })

" Events
" ---

augroup user_plugin_defx
	autocmd!

	" Define defx window mappings
	autocmd FileType defx call <SID>defx_mappings()

	" Delete defx if it's the only buffer left in the window
	autocmd WinEnter * if &filetype == 'defx' && winnr('$') == 1 | bdel | endif

	" Move focus to the next window if current buffer is defx
	autocmd TabLeave * if &filetype == 'defx' | wincmd w | endif

augroup END

" Internal functions
" ---
function! s:jump_dirty(dir) abort
	" Jump to the next position with defx-git dirty symbols
	let l:icons = get(g:, 'defx_git_indicators', {})
	let l:icons_pattern = join(values(l:icons), '\|')

	if ! empty(l:icons_pattern)
		let l:direction = a:dir > 0 ? 'w' : 'bw'
		return search(printf('\(%s\)', l:icons_pattern), l:direction)
	endif
endfunction

function! s:defx_toggle_tree() abort
	" Open current file, or toggle directory expand/collapse
	if defx#is_directory()
		return defx#do_action('open_or_close_tree')
	endif
	return defx#do_action('multi', ['drop'])
endfunction

function! s:defx_mappings() abort
	" Defx window keyboard mappings
	setlocal signcolumn=no expandtab

	nnoremap <silent><buffer><expr> <CR>  defx#do_action('drop')
	nnoremap <silent><buffer><expr> l     <sid>defx_toggle_tree()
	nnoremap <silent><buffer><expr> h     defx#async_action('cd', ['..'])
	nnoremap <silent><buffer><expr> st    defx#do_action('multi', [['drop', 'tabnew'], 'quit'])
	nnoremap <silent><buffer><expr> s     defx#do_action('open', 'botright vsplit')
	nnoremap <silent><buffer><expr> i     defx#do_action('open', 'botright split')
	nnoremap <silent><buffer><expr> P     defx#do_action('open', 'pedit')
	nnoremap <silent><buffer><expr> K     defx#do_action('new_directory')
	nnoremap <silent><buffer><expr> N     defx#do_action('new_multiple_files')
	nnoremap <silent><buffer><expr> dd    defx#do_action('remove_trash')
	nnoremap <silent><buffer><expr> r     defx#do_action('rename')
	nnoremap <silent><buffer><expr> x     defx#do_action('execute_system')
	nnoremap <silent><buffer><expr> .     defx#do_action('toggle_ignored_files')
	nnoremap <silent><buffer><expr> yy    defx#do_action('yank_path')
	nnoremap <silent><buffer><expr> ~     defx#async_action('cd')
	nnoremap <silent><buffer><expr> q     defx#do_action('quit')
	nnoremap <silent><buffer><expr> <Tab> winnr('$') != 1 ?
		\ ':<C-u>wincmd w<CR>' :
		\ ':<C-u>Defx -buffer-name=temp -split=vertical<CR>'
	" Defx's buffer management
	nnoremap <silent><buffer><expr> q      defx#do_action('quit')
	nnoremap <silent><buffer><expr> se     defx#do_action('save_session')
	nnoremap <silent><buffer><expr> <C-r>  defx#do_action('redraw')
	nnoremap <silent><buffer><expr> <C-g>  defx#do_action('print')

	" File/dir management
	nnoremap <silent><buffer><expr><nowait> c  defx#do_action('copy')
	nnoremap <silent><buffer><expr><nowait> m  defx#do_action('move')
	nnoremap <silent><buffer><expr><nowait> p  defx#do_action('paste')
	nnoremap <silent><buffer><expr><nowait> r  defx#do_action('rename')
	nnoremap <silent><buffer><expr> dd defx#do_action('remove_trash')
	nnoremap <silent><buffer><expr> K  defx#do_action('new_directory')
	nnoremap <silent><buffer><expr> N  defx#do_action('new_multiple_files')

	" Jump
	nnoremap <silent><buffer>  [g :<C-u>call <SID>jump_dirty(-1)<CR>
	nnoremap <silent><buffer>  ]g :<C-u>call <SID>jump_dirty(1)<CR>

	" Change directory
	nnoremap <silent><buffer><expr><nowait> \  defx#do_action('cd', getcwd())
	nnoremap <silent><buffer><expr><nowait> &  defx#do_action('cd', getcwd())
	nnoremap <silent><buffer><expr> <BS>  defx#async_action('cd', ['..'])
	nnoremap <silent><buffer><expr> ~     defx#async_action('cd')
	nnoremap <silent><buffer><expr> u   defx#do_action('cd', ['..'])
	nnoremap <silent><buffer><expr> 2u  defx#do_action('cd', ['../..'])
	nnoremap <silent><buffer><expr> 3u  defx#do_action('cd', ['../../..'])
	nnoremap <silent><buffer><expr> 4u  defx#do_action('cd', ['../../../..'])

	" Selection
	nnoremap <silent><buffer><expr> *  defx#do_action('toggle_select_all')
	nnoremap <silent><buffer><expr><nowait> <Space>
		\ defx#do_action('toggle_select') . 'j'

	nnoremap <silent><buffer><expr> S  defx#do_action('toggle_sort', 'Time')
	nnoremap <silent><buffer><expr> C
		\ defx#do_action('toggle_columns', 'indent:mark:filename:type:size:time')

endfunction
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. open defx
 2. open file many times

## Generate a logfile if appropriate

log is empty..

## Screen shot (if possible)

![test3](https://user-images.githubusercontent.com/41671631/83273132-b80f5880-a1fe-11ea-9f1b-020abff4dda2.gif)

**Comment by kristijanhusak** [comment] 2020-05-29 15:09
Does it open if you do `:edit path/to/style.scss` ?

**Comment by glepnir** [comment] 2020-05-29 15:20
@kristijanhusak  i update the mini.vim file.. it open 
![image](https://user-images.githubusercontent.com/41671631/83276304-fc045c80-a202-11ea-903f-ece836cf8fe7.png)

**Comment by Shougo** [comment] 2020-05-30 05:21
> Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}

This is really needed???

And your minimal vimrc is too long.  Please more reduce it.

**Comment by Shougo** [comment] 2020-05-30 05:25
Please upload your opened file or reproduce-able file.
If not, it is not reproduce-able for me.

I will close non reproduce-able issue.

**Comment by Shougo** [comment] 2020-05-30 05:25
I will create more minimal vimrc.
Please wait.

**Comment by Shougo** [comment] 2020-05-30 05:28
Ah, your minimal vimrc is not real...

Because, you have used `git` column.
It is defx-git's feature, but it is not included in the minimal vimrc?
Can I close the issue?

**Comment by Shougo** [comment] 2020-05-30 05:29
```
The reproduce ways from neovim/Vim starting (Required!)

    open defx
    open file many times
```

This is too bad reproduce instructions.
Have you read other issues??

**Comment by Shougo** [comment] 2020-05-30 05:32
This is the real vimrc and reproduce-able instructions.

```vim
set runtimepath+=~/work/defx.nvim
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/

filetype plugin indent on

call defx#custom#option('_', {
      \ 'resume': 1,
      \ 'winwidth': 30,
      \ 'split': 'vertical',
      \ 'direction': 'topleft',
      \ 'show_ignored_files': 0,
      \ 'columns': 'indent:icons:filename',
      \ 'root_marker': ' ',
      \ 'profile': 1,
      \ })

call defx#custom#column('mark', { 'readonly_icon': '', 'selected_icon': '' })

" Events
" ---

augroup user_plugin_defx
  autocmd!

  " Define defx window mappings
  autocmd FileType defx call <SID>defx_mappings()

  " Delete defx if it's the only buffer left in the window
  autocmd WinEnter * if &filetype == 'defx' && winnr('$') == 1 | bdel | endif

  " Move focus to the next window if current buffer is defx
  autocmd TabLeave * if &filetype == 'defx' | wincmd w | endif
augroup END

" Internal functions
" ---
function! s:jump_dirty(dir) abort
  " Jump to the next position with defx-git dirty symbols
  let l:icons = get(g:, 'defx_git_indicators', {})
  let l:icons_pattern = join(values(l:icons), '\|')

  if ! empty(l:icons_pattern)
    let l:direction = a:dir > 0 ? 'w' : 'bw'
    return search(printf('\(%s\)', l:icons_pattern), l:direction)
  endif
endfunction

function! s:defx_toggle_tree() abort
  " Open current file, or toggle directory expand/collapse
  if defx#is_directory()
    return defx#do_action('open_or_close_tree')
  endif
  return defx#do_action('multi', ['drop'])
endfunction

function! s:defx_mappings() abort
  " Defx window keyboard mappings
  setlocal signcolumn=no expandtab

  nnoremap <silent><buffer><expr> <CR>  defx#do_action('drop')
  nnoremap <silent><buffer><expr> l     <sid>defx_toggle_tree()
endfunction
```

I have tested below,

* Open defx by `:Defx`
* Open some files. Because you have not uploaded real reproduce-able instructions.
It means "You can reproduce the problem any of files, OK"
* works fine.

So I close the issue.

**Closed by Shougo** 2020-05-30 05:32 UTC
Labels: cannot reproduce

**Comment by Shougo** [comment] 2020-05-30 05:35
Note:  If other people reproduce the problem, please upload the minimal vimrc with reproduce-able instructions.

**Comment by glepnir** [comment] 2020-05-30 06:01
@Shougo   Please reopen.  I can reproduce with this vimrc, i guess the defx conflict with coc?. 
the file is this [repo](https://github.com/glepnir/go-react-jwt).
```vim
" Your minimal init.vim/vimrc
call plug#begin('~/.vim/plugged')
Plug 'Shougo/defx.nvim'
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
call plug#end()

call defx#custom#option('_', {
	\ 'resume': 1,
	\ 'winwidth': 30,
	\ 'split': 'vertical',
	\ 'direction': 'topleft',
	\ 'show_ignored_files': 0,
	\ 'columns': 'indent:git:icons:filename',
	\ 'root_marker': ' ',
	\ 'profile': 1,
	\ })

augroup user_plugin_defx
	autocmd!
	" Define defx window mappings
	autocmd FileType defx call <SID>defx_mappings()
	" Delete defx if it's the only buffer left in the window
	autocmd WinEnter * if &filetype == 'defx' && winnr('$') == 1 | bdel | endif
	" Move focus to the next window if current buffer is defx
	autocmd TabLeave * if &filetype == 'defx' | wincmd w | endif
augroup END

function! s:defx_toggle_tree() abort
	" Open current file, or toggle directory expand/collapse
	if defx#is_directory()
		return defx#do_action('open_or_close_tree')
	endif
	return defx#do_action('multi', ['drop'])
endfunction

function! s:defx_mappings() abort
	" Defx window keyboard mappings
	setlocal signcolumn=no expandtab
	nnoremap <silent><buffer><expr> l     <sid>defx_toggle_tree()
endfunction
```

![test3](https://user-images.githubusercontent.com/41671631/83320881-fdbf3600-a27d-11ea-9272-0ce1b76a14ac.gif)

**Comment by Shougo** [comment] 2020-05-30 07:26
Really?  I don't want to debug coc.nvim.

**Comment by Shougo** [comment] 2020-05-30 07:33
I have tested it, but I don't reproduce it.
So I keep to close it.

```vim
set runtimepath+=~/work/defx.nvim
set runtimepath+=~/src/coc.nvim
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/

filetype plugin indent on

call defx#custom#option('_', {
	\ 'resume': 1,
	\ 'winwidth': 30,
	\ 'split': 'vertical',
	\ 'direction': 'topleft',
	\ 'show_ignored_files': 0,
	\ 'columns': 'indent:git:icons:filename',
	\ 'root_marker': ' ',
	\ 'profile': 1,
	\ })

augroup user_plugin_defx
	autocmd!
	" Define defx window mappings
	autocmd FileType defx call <SID>defx_mappings()
	" Delete defx if it's the only buffer left in the window
	autocmd WinEnter * if &filetype == 'defx' && winnr('$') == 1 | bdel | endif
	" Move focus to the next window if current buffer is defx
	autocmd TabLeave * if &filetype == 'defx' | wincmd w | endif
augroup END

function! s:defx_toggle_tree() abort
	" Open current file, or toggle directory expand/collapse
	if defx#is_directory()
		return defx#do_action('open_or_close_tree')
	endif
	return defx#do_action('multi', ['drop'])
endfunction

function! s:defx_mappings() abort
	" Defx window keyboard mappings
	setlocal signcolumn=no expandtab
	nnoremap <silent><buffer><expr> l     <sid>defx_toggle_tree()
endfunction
```

My instructions.

* `:Defx ~/src/go-react-jwt`
* open `client/src/views/login/style.css` file by `l` key.

**Comment by glepnir** [comment] 2020-05-30 07:35
@Shougo Just my guess, after I commented the coc, it works fine, I want to know can you reproduce it, I enabled the profile but it just prints defx redrawtime, I can't see what happened.

**Comment by glepnir** [comment] 2020-05-30 07:36
It ’s weird. I can reproduce it easily. It ’s not my problem. My partner also encountered this kind of problem. It happened occasionally. I ’m trying the smallest steps to reproduce it.

**Comment by Shougo** [comment] 2020-05-30 07:37
I don't know, but it may be conflicted.
Because I don't use coc and I don't setup coc.nvim.
I have executed `yarn install --frozen-lockfile`.

**Comment by Shougo** [comment] 2020-05-30 07:39
> @Shougo Just my guess, after I commented the coc, it works fine, I want to know can you reproduce it, I enabled the profile but it just prints defx redrawtime, I can't see what happened.

I have describe it.  I don't reproduce the problem.
Please test it with docker environment(clean environment).

**Comment by Shougo** [comment] 2020-05-30 07:41
I think you have set up `coc.nvim`.

You must describe it.

https://github.com/neoclide/coc.nvim

If not, I will ignore the issue.

**Comment by glepnir** [comment] 2020-05-30 07:43
I did not config coc. just install it. i will test it on docker.
```vim
set runtimepath+=~/.cache/vim/dein/repos/github.com/Shougo/defx.nvim
set runtimepath+=~/.cache/vim/dein/repos/github.com/neoclide/coc.nvim

filetype plugin indent on

call defx#custom#option('_', {
	\ 'resume': 1,
	\ 'winwidth': 30,
	\ 'split': 'vertical',
	\ 'direction': 'topleft',
	\ 'show_ignored_files': 0,
	\ 'columns': 'indent:git:icons:filename',
	\ 'root_marker': ' ',
	\ 'profile': 1,
	\ })

augroup user_plugin_defx
	autocmd!
	" Define defx window mappings
	autocmd FileType defx call <SID>defx_mappings()
	" Delete defx if it's the only buffer left in the window
	autocmd WinEnter * if &filetype == 'defx' && winnr('$') == 1 | bdel | endif
	" Move focus to the next window if current buffer is defx
	autocmd TabLeave * if &filetype == 'defx' | wincmd w | endif
augroup END

function! s:defx_toggle_tree() abort
	" Open current file, or toggle directory expand/collapse
	if defx#is_directory()
		return defx#do_action('open_or_close_tree')
	endif
	return defx#do_action('multi', ['drop'])
endfunction

function! s:defx_mappings() abort
	" Defx window keyboard mappings
	setlocal signcolumn=no expandtab
	nnoremap <silent><buffer><expr> l     <sid>defx_toggle_tree()
endfunction

```

**Comment by Shougo** [comment] 2020-05-30 07:45
Really?  Why it does not work for me?

You may install coc extension.

**Comment by glepnir** [comment] 2020-05-30 07:49
Aha， I forget it. i wil remove all extensions.

**Comment by Shougo** [comment] 2020-05-30 07:49
Oh...

**Comment by glepnir** [comment] 2020-05-30 07:56
@Shougo  when i removed the coc extensions. it works. sorry for this issue,

**Comment by Shougo** [comment] 2020-05-30 07:58
OK.  Please describe what extensions conflict with defx.
I will research it.

**Comment by glepnir** [comment] 2020-05-30 08:07
I found it it's coc-project..

**Comment by Shougo** [comment] 2020-05-30 08:10
I have installed, but I don't reproduce it.

**Comment by glepnir** [comment] 2020-05-30 08:21
@Shougo  use this vimrc and `coc-settings.json` file. then `CocInstall coc-project`
> 
> ```viml
> set runtimepath+=~/.cache/vim/dein/repos/github.com/Shougo/defx.nvim
> set runtimepath+=~/.cache/vim/dein/repos/github.com/neoclide/coc.nvim
> 
> filetype plugin indent on
> 
> call defx#custom#option('_', {
> 	\ 'resume': 1,
> 	\ 'winwidth': 30,
> 	\ 'split': 'vertical',
> 	\ 'direction': 'topleft',
> 	\ 'show_ignored_files': 0,
> 	\ 'columns': 'indent:git:icons:filename',
> 	\ 'root_marker': ' ',
> 	\ 'profile': 1,
> 	\ })
> 
> augroup user_plugin_defx
> 	autocmd!
> 	" Define defx window mappings
> 	autocmd FileType defx call <SID>defx_mappings()
> 	" Delete defx if it's the only buffer left in the window
> 	autocmd WinEnter * if &filetype == 'defx' && winnr('$') == 1 | bdel | endif
> 	" Move focus to the next window if current buffer is defx
> 	autocmd TabLeave * if &filetype == 'defx' | wincmd w | endif
> augroup END
> 
> function! s:defx_toggle_tree() abort
> 	" Open current file, or toggle directory expand/collapse
> 	if defx#is_directory()
> 		return defx#do_action('open_or_close_tree')
> 	endif
> 	return defx#do_action('multi', ['drop'])
> endfunction
> 
> function! s:defx_mappings() abort
> 	" Defx window keyboard mappings
> 	setlocal signcolumn=no expandtab
> 	nnoremap <silent><buffer><expr> l     <sid>defx_toggle_tree()
> endfunction
> ```

```json
use this  `coc-settings.json` file 
```json
{
  "project.dbpath": "~/.cache/vim/.coc-project",
  "project.rootPatterns": [
    ".git",
    "go.mod",
    "jsconfig.json",
    "tsconfig.json",
    "Cargo.toml"
  ],
}
```

**Comment by Shougo** [comment] 2020-05-30 08:26
I have added the file and `~/.cache/vim/.coc-project` is created.
I think coc-project is works.

But I don't reproduce the problem.
Unfortunately, I cannot fix it.

**Comment by glepnir** [comment] 2020-05-30 08:33
Thank you very much for your help. The problem cannot be reproduced after I removed it, so if the problem is reproduced later, I will continue to investigate what happened and report it here.

**Comment by Shougo** [comment] 2020-05-30 08:40
OK.

**Comment by glepnir** [comment] 2020-05-30 08:43
By the way, the configuration of json will cause this problem, another friend of mine can reproduce it,

**Comment by Shougo** [comment] 2020-05-30 08:58
I don't reproduce it unfortunately

**Comment by Shougo** [comment] 2020-05-30 08:59
It seems coc-project configuration

**Comment by IhsanGunay** [comment] 2021-09-17 17:43
``

**Comment by IhsanGunay** [comment] 2021-09-17 17:54
Hi Shougo,

I am having the same problem without coc. I think the autochdir option causes the problem but I am not sure. I used to infrequently get the blank bufffers so the option might just be triggering the edge case that causes defx to mess up the paths. Sometimes it opend `/dir/file` instead of `~/dir/file`, other times it opens `cwd/file` instead of `path/to/file`. Here are the vimrc files I used to reproduce the problem.

test.vim
```
" test.vim
set autochdir

set runtimepath+=~/.local/share/dein/repos/github.com/Shougo/dein.vim
let s:hare = '~/test/test.toml'
let g:dein#auto_recache = 1


if dein#load_state('~/.local/share/dein')
 call dein#begin('~/.local/share/dein')
 call dein#load_toml(s:hare)
 call dein#end()
 call dein#save_state()
endif

filetype plugin indent on
syntax on
```

test.toml
```
# test.toml

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
nnoremap - <Cmd>Defx `escape(expand('%:p:h'), ' :')` -search=`expand('%:p')`<CR>
'''
hook_post_source = '''
  call defx#custom#option('_', {
  \ 'columns': 'indent:git:icons:filename:mark',
  \ 'ignored_files': '.git,*cache*,.pki',
  \ 'vertical_preview': 1,
  \ 'auto_cd': 1,
  \ 'toggle': 1,
  \ 'winwidth': 30,
  \ 'split': 'vertical',
  \ 'direction': 'topleft',
  \ })
'''

[ftplugin]
defx = '''
  nnoremap <silent><buffer><expr> h
  \ defx#do_action('cd', ['..'])

  nnoremap <silent><buffer><expr> l
  \ defx#is_directory() ?
  \ defx#do_action('open_directory') :
  \ defx#do_action('multi', ['drop', 'quit'])

  nnoremap <silent><buffer><expr> ~
  \ defx#do_action('cd')

  nnoremap <silent><buffer><expr> \
  \ defx#do_action('cd', getcwd())
'''
```

**Comment by Shougo** [comment] 2021-09-18 05:05
Really?  I don't want to support `autochdir` option.

**Comment by Shougo** [comment] 2021-09-18 05:09
I have added `autochdir` check.  Please test.
