### ISSUE TITLE
Error when open file

### ISSUE THREAD

**Issue by thevan96** [Shougo/defx.nvim#274] opened 2020-11-22 12:49 UTC
## When i build system notetalking, when open file then error 
![Screenshot 2020-11-22 at 19 48 11](https://user-images.githubusercontent.com/47932916/99904138-a87b5300-2cfb-11eb-85bc-500ef351a362.png)

## Config nvim width defx, neovim version dev
Plug 'Shougo/defx.nvim', { 'do': ':UpdateRemotePlugins'  }
augroup defxConfig
  autocmd FileType defx set nobuflisted
  autocmd BufWritePost * call defx#redraw()
  autocmd FileType defx call s:defx_my_settings()
augroup end
nnoremap <silent><leader>f :Defx -search=`expand('%:p')`
      \ -columns=space:indent:icon:mark:filename
      \ -show-ignored-files
      \ -resume -listed<cr>
nnoremap <silent><leader>F :Defx
      \ -columns=space:indent:icon:mark:filename
      \ -show-ignored-files
      \ -resume -listed<cr>

function! s:defx_my_settings() abort
  call defx#custom#column('icon', {
        \ 'directory_icon': '+●',
        \ 'opened_icon': '=○',
        \ })
  call defx#custom#column('filename', {
        \ 'min_width': 50,
        \ 'max_width': 50,
        \ })
  nnoremap <silent><buffer><expr> <cr>
        \ defx#do_action('open')
  nnoremap <silent><buffer><expr> u
        \ defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> o
        \ defx#do_action('open_or_close_tree')
  nnoremap <silent><buffer><expr> dd
        \ defx#do_action('remove_trash')
  nnoremap <silent><buffer><expr> yy
        \ defx#do_action('copy')
  nnoremap <silent><buffer><expr> mv
        \ defx#do_action('move')
  nnoremap <silent><buffer><expr> p
        \ defx#do_action('paste')
  nnoremap <silent><buffer><expr> mk
        \ defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> t
        \ defx#do_action('new_file')
  nnoremap <silent><buffer><expr> T
        \ defx#do_action('new_multiple_files')
  nnoremap <silent><buffer><expr> rn
        \ defx#do_action('rename')
  nnoremap <silent><buffer><expr> *
        \ defx#do_action('toggle_select_all')
  nnoremap <silent><buffer><expr> a
        \ defx#do_action('toggle_select')
  nnoremap <silent><buffer><expr> A
        \ defx#do_action('toggle_select_visual')
  nnoremap <silent><buffer><expr> cl
        \ defx#do_action('clear_select_all')
  nnoremap <silent><buffer><expr> yp
        \ defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> i
        \ defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> R
        \ defx#do_action('redraw')
  nnoremap <silent><buffer><expr> <esc>
        \ defx#do_action('quit')
  nnoremap <silent><buffer><expr> j 'j'
  nnoremap <silent><buffer><expr> k 'k'
endfunction

**Comment by Shougo** [comment] 2020-11-22 13:38
Closing.  Because you have not upload the reproduce instruction with minimal vimrc.
Have you read the issue template?

**Closed by Shougo** 2020-11-22 13:38 UTC

**Comment by Shougo** [comment] 2020-11-22 13:41
Please read and compare with other issues like this.
https://github.com/Shougo/defx.nvim/issues/272

**Comment by Shougo** [comment] 2020-11-22 13:47
I have read the code and I don't know why the error is occurred.
Minimal vimrc and the reproduce instructions are required!

**Comment by Shougo** [comment] 2020-12-05 22:36
Please use the latest version.

**Comment by Shougo** [comment] 2020-12-09 06:08
It is already fixed in the latest version.
