### ISSUE TITLE
Auto close defx buffer after opening a new file or dir

### ISSUE THREAD

**Issue by viniarck** [Shougo/defx.nvim#16] opened 2018-08-19 12:49 UTC
Hi, @Shougo. 

Is there a better way to automatically close the defx buffer whenever I complete an `defx#do_action('open')`?  I'm doing this way:

```
autocmd BufReadPre,FileReadPre * call s:DelDefxBuffer()

function! s:DelDefxBuffer()
  if bufexists("[defx]")
    exe 'bdelete \[defx\]'
  endif
endfunction
```

Thanks!

**Comment by kristijanhusak** [comment] 2018-08-19 13:13
If you just want to hide it from buffera list, try this:

`autocmd FileType defx setlocal nobuflisted`

**Comment by Shougo** [comment] 2018-08-19 13:45
@viniarck Why the feature is needed?  Please describe it more.

**Comment by wsdjeg** [comment] 2018-08-19 13:54
@Shougo some plugins such as airline, use `&buflisted` option to check if this buffer should be listed on tabline.

**Comment by viniarck** [comment] 2018-08-19 14:03
Hi @Shougo,

I used to use [justinmk/vim-dirvish](https://github.com/justinmk/vim-dirvish) plugin, and to me it feels natural that whenever I open a new file or a new directory the buffer of the file manager shouldn't be in my buffer list anymore. And, if I were to explore again, I'd invoke the file manager again.

@kristijanhusak, thanks for the tip. I'd rather close it though because when I quit vim I don't want to have unhidden buffers open.

**Comment by kristijanhusak** [comment] 2018-08-19 14:12
@Shougo maybe there should be an action for closing defx buffer, because there's no really good way to do it manually. I added this mapping for closing it:
```
nnoremap <silent><buffer> q :call execute('bn|bw') 
```
But looks a bit hacky. There must be a better way.

**Comment by Shougo** [comment] 2018-08-19 22:40
> @kristijanhusak, thanks for the tip. I'd rather close it though because when I quit vim I don't want to have unhidden buffers open.

I don't understand the behavior.
Please describe it with the example.

**Closed** 2018-08-21 00:28 UTC
Labels: enhancement

**Comment by viniarck** [comment] 2018-08-21 00:36
Hi @Shougo, I recorded a screencast demo comparing this dirvish, I recorded with termtosvg, you can open it with firefox.

[demo.zip](https://github.com/Shougo/defx.nvim/files/2304280/demo.zip)

As @kristijanhusak mentioned, this also worked as a workaround `autocmd FileType defx setlocal nobuflisted`.

With dirvish I have this command to open the buffer `  autocmd FileType dirvish nnoremap <buffer> l :<C-U>.call dirvish#open("edit",0)<CR>`

**Comment by viniarck** [comment] 2018-08-21 00:36
Thanks guys! :D

**Comment by Shougo** [comment] 2018-08-21 00:49
I have checked the sreencasts.
The feature is already implemented, so the problem is gone.
