### ISSUE TITLE
Why the 2nd level of tree nodes is indent with two spaces?

### ISSUE THREAD

**Issue by zoumi** [Shougo/defx.nvim#303] opened 2021-07-07 02:30 UTC
Look at the screenshot:
![Snipaste_2021-07-07_10-31-07](https://user-images.githubusercontent.com/5162901/124691499-7a572600-df0e-11eb-8568-52d5dc33ddbb.jpg)

**Comment by Shougo** [comment] 2021-07-07 04:49
You have ignored the issue template and you have not uploaded minimal vimrc.
We have not ESP skills.

Closing.

**Comment by Shougo** [comment] 2021-07-07 04:49
> **Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

Please read the issue template header.  I already have warned.

**Comment by zoumi** [comment] 2021-07-07 14:06
@Shougo 
The extra space is added at
https://github.com/Shougo/defx.nvim/blob/master/rplugin/python3/defx/view.py#L767

**Comment by Shougo** [comment] 2021-07-08 00:10
> I don't think this is desired.

It is desired.  The padding is needed.
Because if it is not exists, defx cannot align columns.

And why do you ignore my issue template.  Please describe it for me.
I need to reproduce your problem.

**Comment by Shougo** [comment] 2021-07-08 00:44
Ah, I get the problem.  I have reproduced.

**Comment by Shougo** [comment] 2021-07-08 00:49
I have reproduced the problem with my minimal vimrc.  So I can fix it.
But it does not mean you don't need to upload minimal vimrc.

**Comment by Shougo** [comment] 2021-07-08 01:20
Your fix works with default configuration.
But it does not work with the config.

```vim
  call defx#custom#column('icon', {
          \ 'directory_icon': '+',
          \ 'opened_icon': '-',
          \ 'root_icon': ' ',
          \ })
```

**Comment by Shougo** [comment] 2021-07-08 01:25
Hm... No magic.

**Comment by zoumi** [comment] 2021-07-08 02:07
Sorry for ignoring the issue template.
The reason is:
If you can't locate the bug at your first glance, I will try to debug it myself.
But I'm really sorry for not pasting my defx's config.

```vim
call defx#custom#option('_', {
            \ 'winwidth': 30,
            \ 'split': 'vertical',
            \ 'direction': 'botright',
            \ 'show_ignored_files': 0,
            \ 'buffer_name': '',
            \ 'columns' : 'indent:git:filename:type',
            \ 'toggle': 0,
            \ 'resume': 1,
            \ 'root_marker':'@'
            \ })
```

**Comment by zoumi** [comment] 2021-07-08 02:12
I didn't use defx-git. But put it in "columns" doesn't matter.

**Comment by Shougo** [comment] 2021-07-08 04:47
>If you can't locate the bug at your first glance, I will try to debug it myself.

It need to wait your response.  I need to investigate the problem ASAP.

**Comment by Shougo** [comment] 2021-07-09 05:05
Finally I have fixed the problem!

**Closed** 2021-07-09 05:05 UTC
Labels: bug
