### ISSUE TITLE
b:defx['paths'] dont update

### ISSUE THREAD

**Issue by zgpio** [Shougo/defx.nvim#115] opened 2019-04-04 10:34 UTC
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

## Environment Information

 * defx version(SHA1): 3d36fea

 * OS: Linux

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set rtp+=~/test_nvim/defx.nvim/
```

## The reproduce ways from neovim/Vim starting (Required!)
 1. `nvim -u init.vim`
 1. `:Defx ~` and check `b:defx.paths`, for me, it is `['/home/zgp/']`
 1. `:Defx ~ ~` and check `b:defx.paths` again, for me, it is `['/home/zgp/']`, but `['/home/zgp/', '/home/zgp/']` be expected.
 1. You will find that the paths are not updated to two item,  If I don't misunderstand the purpose of the paths.

## Try to fix it
I found that the window recovery here ignores the changes of the paths: 
https://github.com/Shougo/defx.nvim/blob/3d36feaf41eb1c6a8411dae34964057783179ad1/rplugin/python3/defx/view.py#L320-L327

**Comment by Shougo** [comment] 2019-04-04 12:42
I don't understand.

Why you don't upload the minimal vimrc?

I will close the issue.
Because I don't reproduce it.

**Comment by Shougo** [comment] 2019-04-04 12:42
>Warning: I will close the issue without the minimal init.vim and the reproduction instructions.

Here.

**Comment by Shougo** [comment] 2019-04-04 12:46
I have tested and I don't reproduce your problem.
`b:defx['paths']` is updated.

**Comment by zgpio** [comment] 2019-04-04 12:52
Sorry for that, Updated.

**Closed** 2019-04-04 12:58 UTC
Labels: cannot reproduce

**Comment by zgpio** [comment] 2019-04-04 13:01
In fact, I want to contribute to this project, but after reading the implementation, I feel that there is a lot of work to do, such as source documentation. @Shougo

**Comment by Shougo** [comment] 2019-04-04 13:08
> In fact, I want to contribute to this project, but after reading the implementation, I feel that there is a lot of work to do, such as source documentation.

The souce ocumentation is nothing.  It may be changed later.
And it is so useful?  In vimfiler, no one does not create the source.

**Comment by zgpio** [comment] 2019-04-04 13:14
Sorry for that, I mean source code comment, defx implementation is difficult for me to understand, there is little comment on important data structures, I can only understand it myself, maybe my development experience is not enough. @Shougo

**Comment by Shougo** [comment] 2019-04-04 13:20
Unfortunately, it is feature.
But you can understand easily than vimfiler which written in Vim script.
